### PR TITLE
fix: fix repeat play issue

### LINKED ISSUE #189: Repeated clicking to play in DEMO will cause abnormal screen.
1. Jump to http://localhost:8000/demo/1_1-decode-video
2. Repeated clicking 启动

https://github.com/user-attachments/assets/26fdef05-4f45-4ae9-b744-2ed6bbc75367

### PR DESCRIPTION
**Pull request by Yukiniro**
Closes #189

### CODE REVIEW

File: doc-site/docs/demo/decode-video.tsx [hunk 1]
```diff
@@ -8,13 +8,17 @@ const videos = assetsPrefix({
   'bear.mp4': 'video/bear-vp9.mp4',
 });
 
+let currentClip = null as null | MP4Clip;
+
 async function start(
```
Comment (hughfenghen) [inline doc-site/docs/demo/decode-video.tsx:13]: 建议实现

```js
// 初始空函数
let stop = () => {}
async function start (...) {
  // start 前，先 stop 上次运行的任务
  stop()

  // 已有实现 ...

  // 每次 start ，通过闭包持有当前 clip，timer，这样只需要一个有语义变量（stop）就能清理上次运行的任务
 stop = () => {
    clearInterval(timer);
    clip.destroy();
 }
}
```

**Review by hughfenghen — COMMENTED** [review]
请参考建议代码实现

File: doc-site/docs/demo/decode-video.tsx (hunk 1 above)
Comment (Yukiniro) [reply doc-site/docs/demo/decode-video.tsx:13]: I will try.
